server:
  port: 8080
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/buffer_product
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update